services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - inception

volumes:
  mariadb_data:

networks:
  inception:
    driver: bridge
