services:
  # ---------- MariaDB Service ----------
  mariadb:
    container_name: mariadb
    image: mariadb:hutzig  # This will be overridden by the build context below
    restart: always
    environment:
      # Environment variables for database setup (provided by .env)
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_USER_PWD=${DB_USER_PWD}
      - DB_ROOT_USER=${DB_ROOT_USER}
      - DB_ROOT_PWD=${DB_ROOT_PWD}
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile  # Uses a custom Dockerfile for MariaDB
    volumes:
      - wordpress_db:/var/lib/mysql  # Persistent data volume for database
    networks:
      - inception  # Connects to the custom bridge network

  # ---------- WordPress Service ----------
  wordpress:
    container_name: wordpress
    image: wordpress:hutzig  # Overridden by the build context below
    restart: always
    environment:
      # WordPress config + connection to database
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_USER_PWD=${DB_USER_PWD}
      - DB_HOST=${DB_HOST}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PWD=${WP_ADMIN_PWD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PWD=${WP_USER_PWD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile  # Custom WordPress Dockerfile
    depends_on:
      - mariadb  # Ensures DB starts before WordPress
    volumes:
      - wordpress_files:/var/www/html  # Mount persistent WordPress content
    networks:
      - inception

  # ---------- NGINX Service ----------
  nginx:
    container_name: nginx
    image: nginx:hutzig  # Overridden by build context
    restart: always
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile  # Custom NGINX Dockerfile
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"  # Expose HTTPS port to host
    volumes:
      - wordpress_files:/var/www/html:ro  # Read-only access to WP files
    networks:
      - inception

# ---------- Named Volumes ----------
volumes:
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress  # WordPress files stored on host

  wordpress_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb  # MariaDB data stored on host

# ---------- Network ----------
networks:
  inception:
    name: inception
    driver: bridge  # Default isolated network for all services
